# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print([x for x in dir(np) if "dot" in x.lower()])
print(np.show_config)
print(np.__config__)
print(np.dot.__doc__)

2.3.3
['dot', 'tensordot', 'vdot', 'vecdot']
<function show_config at 0x0000017C53BCF2E0>
<module 'numpy.__config__' from 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\__config__.py'>

dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS 

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector=np.zeros(10,dtype=int)
print(null_vector)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [47]:
np.size(null_vector)
print([x for x in dir(np.ndarray) if "byte" in x.lower()])
# output of this gives nbytes as one of the attru=ibutes
print(null_vector.nbytes)
print(np.ndarray.nbytes.__doc__)


['byteswap', 'nbytes', 'newbyteorder', 'tobytes']
80
Total bytes consumed by the elements of the array.

    Notes
    -----
    Does not include memory consumed by non-element attributes of the
    array object.

    See Also
    --------
    sys.getsizeof
        Memory consumed by the object itself without parents in case view.
        This does include memory consumed by non-element attributes.

    Examples
    --------
    >>> import numpy as np
    >>> x = np.zeros((3,5,2), dtype=np.complex128)
    >>> x.nbytes
    480
    >>> np.prod(x.shape) * x.itemsize
    480


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [48]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vec=np.zeros(10,dtype=int)
vec[4]=1
print(vec)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
vec=np.array([1,2,3,4,5])
vec=vec[::-1]
print(vec)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [52]:
matrix=np.arange(9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
[x for x in dir(np) if "zero" in x.lower()]
print(np.nonzero.__doc__)
vector=np.array([1,2,0,0,4,0])
print(np.nonzero(vector))


Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order.

To group the indices by element, rather than dimension, use `argwhere`,
which returns a row for each non-zero element.

.. note::

   When called on a zero-d array or scalar, ``nonzero(a)`` is treated
   as ``nonzero(atleast_1d(a))``.

   .. deprecated:: 1.17.0

      Use `atleast_1d` explicitly if this behavior is deliberate.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the input array.

Notes
-----
While the no

#### 11. Create a 3x3 identity matrix (★☆☆)

In [6]:
[x for x in dir(np) if "identity" in x.lower()]
# outputs identity
#print(np.identity.__doc__)
matrix_ones=np.identity(3,dtype=int)
print(matrix_ones)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [10]:
[x for x in dir(np) if "rand" in x.lower()]
# the above outputs random 
#print(np.random.__doc__)
#print(np.random())-> couldnt figure out whther it was a function or not because no paramter was mentioned
# so i just called it without passing any and the error showed that its a module!
[x for x in dir(np.random) if "rand" in x.lower()]
matches = [x for x in dir(np.random) if "rand" in x.lower()]

for name in matches:
    print(f"\n{name}")
    print("-"*30)

    obj = getattr(np.random, name)

    if callable(obj):
        print(obj.__doc__[:200])
# well what we can do is that we can create an array and append a rand int 
matrix=np.random.randint(1,101,27)
matrix=np.reshape(matrix,(3,3,3))
print(matrix)


RandomState
------------------------------

    RandomState(seed=None)

    Container for the slow Mersenne Twister pseudo-random number generator.
    Consider using a different BitGenerator with the Generator container
    instead.

    `Ran

__RandomState_ctor
------------------------------
Return a RandomState instance.

This function exists solely to assist (un)pickling.

Note that the state of the RandomState returned here is irrelevant, as this
function's entire purpose is to return 

mtrand
------------------------------

rand
------------------------------

        rand(d0, d1, ..., dn)

        Random values in a given shape.

        .. note::
            This is a convenience function for users porting code from Matlab,
            and wraps `random_

randint
------------------------------

        randint(low, high=None, size=None, dtype=int)

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete un

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
vector=np.random.randint(1,1001,100).reshape((10,10))
[x for x in dir(np) if "mini" in x.lower()]
minimum_value=np.min(vector)
maximum_value=np.max(vector)
print(f"The min value is {minimum_value}")
print(f"The max value is {maximum_value}")

The min value is 27
The max value is 997


In [31]:
rand_vector=np.random.randint(1,101,10)
print(rand_vector)
average=np.mean(rand_vector)
print(f"The average value is {average}")
matches=[x for x in dir(np) if "mean" in x.lower()]
for name in matches:
    obj=getattr(np,name)
    print(f"\n{name}")
    print(30*"-")
    if hasattr(obj,"__doc__"):# kya obj k paas __doc__ hai
        print(obj.__doc__[:200])


[68 37  1 26 61 52 86 50 66 56]
The average value is 50.3

mean
------------------------------

Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float6

nanmean
------------------------------

Compute the arithmetic mean along the specified axis, ignoring NaNs.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specifie


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [43]:
matrix=np.identity(5,dtype=int)
#matrix[0]=1
#print(matrix[0])
#print(matrix[4])
#print(matrix[:,0])
#print(matrix[:,4])
matrix_0s=np.zeros((5,5),dtype=int)
print(matrix_0s)
matrix_0s[0]=1
matrix_0s[4]=1
matrix_0s[:,0]=1
matrix_0s[:,4]=1
print(matrix_0s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
vec=np.array([1,2,3,4])
vec=np.hstack((0,vec))
vec=np.hstack((vec,0))
print(vec)
matrix=np.ones((5,5),dtype=int)
vec1=np.zeros(5,dtype=int)
vec2=np.zeros((7,1),dtype=int)
matrix=np.vstack((vec1,matrix))
matrix=np.vstack((matrix,vec1))
matrix=np.hstack((matrix,vec2))
matrix=np.hstack((vec2,matrix))
print(matrix)



[0 1 2 3 4 0]
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
0*np.nan# output is nan
np.nan==np.nan # output is false
np.inf>np.nan # output is false 
np.nan-np.nan# output is nan
np.nan in set([np.nan]) # output is true
0.3==2*0.1 # output is false(np.isclose(a,b) is used to check for search equality)

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [69]:
#atrix=np.zeros((5,5),dtype=int)
#for i in range(4):
#    matrix[i+1][i]=i+1;
#print(matrix)

#this was the initial approach!
matches=[x for x in dir(np) if "diag" in x.lower()]
#print(matches)
array=np.diag([1,2,3,4],k=-1)
print(array)

# therese one more method and that is integer array indexing

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [92]:
matrix=np.array([[1,0],[0,1]])
matrix=np.hstack((matrix,matrix,matrix,matrix))
matrix=np.vstack((matrix,matrix,matrix,matrix))
print(matrix)
# method -2:
matrix=np.zeros((8,8),dtype=int)
matrix[1::2,1::2]=1
matrix[::2,::2]=1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [103]:
# i guess there has to be some function related to idnex 
print([x for x in dir(np) if "ind" in x.lower()])
help(np.unravel_index)
index_value=np.unravel_index(100,(6,7,8))
index_value# output:(np.int64(1), np.int64(5), np.int64(4))-> some weird output!
clean_index=tuple(map(int,index_value))
print(clean_index)

['diag_indices', 'diag_indices_from', 'index_exp', 'indices', 'mask_indices', 'ndindex', 'ravel_multi_index', 'remainder', 'tril_indices', 'tril_indices_from', 'triu_indices', 'triu_indices_from', 'unravel_index']
Help on _ArrayFunctionDispatcher in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')

    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.

    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.

    Returns
    -------
    unraveled_coords : tuple of ndarr

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [18]:
matrix=np.tile([[1,0],[0,1]],(4,4))
print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
# lets take a random  matrix
matrix=np.random.randint(1,11,(5,5))
#matrix=np.array([[3,4],[4,3]])# just for verification!
print(matrix)
product=matrix*matrix
sq_sum=np.sum(product,axis=0)
root_square_sum=np.sqrt(sq_sum)
matrix=matrix/root_square_sum# broadcasting used here
print(matrix)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [41]:
color=np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])
print(color)
pixel = np.array((255,0,0,255), dtype=color)
print(pixel['r'])
print(np.uint8)
print(np.dtype(np.uint8))
print(np.iinfo(np.uint8))
color.itemsize

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
255
<class 'numpy.uint8'>
uint8
Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------



4

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [107]:
matches=[x for x in dir(np) if 'dot' in x.lower()]
#for match in matches:
 #   obj=getattr(np,match)
  #  print("\n")
   # print("*"*30)
    #if(callable(obj)):
     #   print(obj.__doc__)
matrix_1=np.arange(1,16).reshape((5,3))
print(matrix_1)
matrix_2=np.arange(7,13).reshape((3,2))
print(matrix_2)
multiplication=np.dot(matrix_1,matrix_2)
print(multiplication)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]
 [220 244]
 [301 334]
 [382 424]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
vec=np.arange(1,10)
bool_index=(vec>3)&(vec<8)
vec[bool_index]=-1*vec[bool_index]
print(vec)

[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [40]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [55]:
arr=np.arange(1,5)
print(arr<<2)
print(2<<arr)
print(2<<arr>>2)
print(-arr)
1j*arr
arr/1/1
# arr<arr> this one is incorrect

SyntaxError: invalid syntax (541858436.py, line 8)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [89]:
#np.array(0) / np.array(0) # nan is the output with warning!(in float)
#np.array(0) // np.array(0)#nan is the output with warning (in iny)
#np.array([np.nan]).astype(int).astype(float)# some very big negative  number with warning!
#print(0/0)# a zero division error
# 3rd one give wanrng and otehr give error


C:\Users\DELL\AppData\Local\Temp\ipykernel_28636\2013943421.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)# some very big number with warning!


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [62]:
3//5

0

#### 30. How to find common values between two arrays? (★☆☆)

In [78]:
arr_1=np.arange(1,11)
arr_2=np.arange(7,15)
common_values=[x for x in arr_1 if x in arr_2]
common_values=np.array(list(map(int,common_values)))
print(common_values)

# theres a dedicated function also and that is intersectid!

[ 7  8  9 10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [92]:
with np.errstate(all='ignore'):
    print(np.array(0)/np.array(0))

nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [101]:
#np.sqrt(-1)==np.emath.sqrt(-1)
# the left side follows the normal math and gives you nan + warning
# the right side follows extended math and gives you ij and hence both are not equa;

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [134]:
matches=[x for x in dir(np) if 'date' in x.lower()]


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
#help(np.datetime64)
d = np.datetime64('today')
duration

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [149]:
# if we do 
#A=A+B-> this creates a temp array and then assign A to that Temp array!
A=np.array([1,2,3,4],dtype=float)
B=np.array([5,6,7,8],dtype=float)
# making it float is neccesary because on idvison A will become float and if A is not float from ear;ier then
# casting eroro will occur

np.add(A,B,out=B)
print(B)
np.divide(A,-2,out=A)
np.multiply(A,B)


[ 6.  8. 10. 12.]


array([ -3.,  -8., -15., -24.])

#### .036. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [154]:
A=np.array([-1.5,-2.2,3.2,4,5])
print(A.astype(int))
print(np.ceil(A))
print(np.trunc(A))
print(np.floor(A))
print(A//1)


[-1 -2  3  4  5]
[-1. -2.  3.  4.  5.]
[-2. -3.  3.  4.  5.]
[-2. -3.  3.  4.  5.]
[-1. -2.  4.  4.  5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [162]:
mat_1=np.arange(0,5)
mat_1=np.tile(mat_1,(5,1))
print(mat_1)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [163]:
vec=np.random.rand(10)
print(vec)

[0.37591635 0.65731237 0.939214   0.09144878 0.41824029 0.27708829
 0.99172788 0.34179873 0.626274   0.66737766]


#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)